# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyUIBasicDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 632)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30,60, 41, 16))
        self.label_2.setObjectName("label_2")

        self.label_uuid = QtWidgets.QLabel(Form)
        self.label_uuid.setGeometry(QtCore.QRect(20, 110, 140, 36))
        self.label_uuid.setObjectName("label_uuid")
        self.label_weight = QtWidgets.QLabel(Form)
        self.label_weight.setGeometry(QtCore.QRect(180, 110, 140, 36))
        self.label_weight.setObjectName("label_weight")
        self.label_state = QtWidgets.QLabel(Form)
        self.label_state.setGeometry(QtCore.QRect(25, 110, 1, 36))
        self.label_state.setObjectName("label_state")
        self.label_uuid.setFont(QtGui.QFont("Arial", 13))
        self.label_weight.setFont(QtGui.QFont("Arial", 13))
        self.label_state.setFont(QtGui.QFont("Arial", 1))
        self.label_uuid.setStyleSheet("background-color: lightgray;")
        self.label_weight.setStyleSheet("background-color: lightgray;")

        self.ComboInterface = QtWidgets.QComboBox(Form)
        self.ComboInterface.setGeometry(QtCore.QRect(90, 20, 461, 22))
        self.ComboInterface.setObjectName("ComboInterface")
        self.ComboDevice = QtWidgets.QComboBox(Form)
        self.ComboDevice.setGeometry(QtCore.QRect(90, 60, 461, 22))
        self.ComboDevice.setObjectName("ComboDevice")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 531, 441))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(570, 30, 201, 101))
        self.groupBox.setObjectName("groupBox")
        self.BtnEnumInterface = QtWidgets.QPushButton(self.groupBox)
        self.BtnEnumInterface.setGeometry(QtCore.QRect(30, 20, 141, 23))
        self.BtnEnumInterface.setObjectName("BtnEnumInterface")
        self.BtnOpenInterface = QtWidgets.QPushButton(self.groupBox)
        self.BtnOpenInterface.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.BtnOpenInterface.setObjectName("BtnOpenInterface")
        self.BtnCloseInterface = QtWidgets.QPushButton(self.groupBox)
        self.BtnCloseInterface.setGeometry(QtCore.QRect(110, 60, 91, 23))
        self.BtnCloseInterface.setObjectName("BtnCloseInterface")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 160, 201, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.BtnEnumDevice = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnEnumDevice.setGeometry(QtCore.QRect(30, 20, 141, 23))
        self.BtnEnumDevice.setObjectName("BtnEnumDevice")
        self.BtnOpenDevice = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnOpenDevice.setGeometry(QtCore.QRect(10, 60, 81, 23))
        self.BtnOpenDevice.setObjectName("BtnOpenDevice")
        self.BtnCloseDevice = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnCloseDevice.setGeometry(QtCore.QRect(110, 60, 81, 23))
        self.BtnCloseDevice.setObjectName("BtnCloseDevice")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 420, 201, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.RadioContinuousMode = QtWidgets.QRadioButton(self.groupBox_4)
        self.RadioContinuousMode.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.RadioContinuousMode.setObjectName("RadioContinuousMode")
        self.RadioTriggerMode = QtWidgets.QRadioButton(self.groupBox_4)
        self.RadioTriggerMode.setGeometry(QtCore.QRect(110, 20, 89, 16))
        self.RadioTriggerMode.setObjectName("RadioTriggerMode")
        self.BtnStart = QtWidgets.QPushButton(self.groupBox_4)
        self.BtnStart.setGeometry(QtCore.QRect(10, 50, 81, 23))
        self.BtnStart.setObjectName("BtnStart")
        self.BtnStop = QtWidgets.QPushButton(self.groupBox_4)
        self.BtnStop.setGeometry(QtCore.QRect(110, 50, 81, 23))
        self.BtnStop.setObjectName("BtnStop")
        self.CheckTriggerbySoftware = QtWidgets.QCheckBox(self.groupBox_4)
        self.CheckTriggerbySoftware.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.CheckTriggerbySoftware.setObjectName("CheckTriggerbySoftware")
        self.BtnTriggerOnce = QtWidgets.QPushButton(self.groupBox_4)
        self.BtnTriggerOnce.setGeometry(QtCore.QRect(90, 90, 101, 23))
        self.BtnTriggerOnce.setObjectName("BtnTriggerOnce")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 280, 91, 55))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_nFrame = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_nFrame.setGeometry(QtCore.QRect(10, 20, 71, 23))
        self.lineEdit_nFrame.setObjectName("lineEdit_nFrame")
        self.lineEdit_nFrame.setPlaceholderText("จำนวน frame")
        self.lineEdit_nFrame.setText("7")
        self.lineEdit_nFrame.setEnabled(False)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(680, 280, 91, 55))
        self.groupBox_6.setObjectName("groupBox_6") 
        self.lineEdit_amountBanana = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_amountBanana.setGeometry(QtCore.QRect(10, 20, 71, 23))
        self.lineEdit_amountBanana.setObjectName("lineEdit_amountBanana")
        self.lineEdit_amountBanana.setPlaceholderText("จำนวนกล้วย")
        self.lineEdit_amountBanana.setText("5")
        self.lineEdit_amountBanana.setEnabled(False)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(570, 350, 201, 55))
        self.groupBox_5.setObjectName("groupBox_5")
        self.BtnGetData1 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnGetData1.setGeometry(QtCore.QRect(5, 20, 105, 23))
        self.BtnGetData1.setObjectName("BtnGetData1")
        self.BtnGetData1.setEnabled(False)
        self.BtnGetData2 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnGetData2.setGeometry(QtCore.QRect(112, 20, 85, 23))
        self.BtnGetData2.setObjectName("BtnGetData2")
        self.BtnGetData2.setEnabled(True)





        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BasicDemo"))
        self.label.setText(_translate("Form", "Interface"))
        self.label_2.setText(_translate("Form", "Device"))

        
        self.groupBox.setTitle(_translate("Form", "Capture card"))
        self.BtnEnumInterface.setText(_translate("Form", "Find interface"))
        self.BtnOpenInterface.setText(_translate("Form", "Enable Interface"))
        self.BtnCloseInterface.setText(_translate("Form", "Disable interface"))
        self.groupBox_2.setTitle(_translate("Form", "Device"))
        self.BtnEnumDevice.setText(_translate("Form", "Find device"))
        self.BtnOpenDevice.setText(_translate("Form", "Enable device"))
        self.BtnCloseDevice.setText(_translate("Form", "Disable device"))
        self.groupBox_4.setTitle(_translate("Form", "Image Acquisition"))
        self.RadioContinuousMode.setText(_translate("Form", "Start continuous mode"))
        self.RadioTriggerMode.setText(_translate("Form", "Start trigger mode"))
        self.BtnStart.setText(_translate("Form", "Start Grabbing"))
        self.BtnStop.setText(_translate("Form", "Stop Grabbing"))
        self.CheckTriggerbySoftware.setText(_translate("Form", "Software"))
        self.BtnTriggerOnce.setText(_translate("Form", "Soft trigger once"))
        self.groupBox_3.setTitle(_translate("Form", "Setting Frame"))
        self.groupBox_5.setTitle(_translate("Form", "Open server"))
        self.BtnGetData1.setText(_translate("Form", "Not Change Banana")) #ใช้น้ำหนักที่ครั้งแรกนำเข้ามา
        self.BtnGetData2.setText(_translate("Form", "Change Banana")) #ใช้น้ำหนักใหม่ทุกครั้งที่ยกออกแล้วแขวนใหม่
        self.groupBox_6.setTitle(_translate("Form", "Amount Banana"))

